포트폴리오 생성 모달 추가
bssm-portfolio/app pull request #4
Opened 2023-01-06 16:42 UTC by pkiop

## 지라 이슈

https://qkrjh0904.atlassian.net/browse/BSSMH-64

## 스크린샷

https://user-images.githubusercontent.com/34783156/211057221-251985d9-2eb8-44ee-96c4-506fb165cd1f.mp4

## 변경한 것

* 포트폴리오 업로드 모달 추가 (다음 버튼 이후 동작 미구현)
* 파일 업로드 UI 추가 (드래그엔드롭 업로드 구현 필요)

2023-01-06 18:03 UTC, J1min commented on hooks/useModal.ts
> +  const closeModal = () => {
선생님 제 생각엔 closeModal에선 따로 
```tsx
setModal({
  title: "",
  content: null,
  visible: false,
});
```
을 해주지 않아도 open을 할 때 매번 값이 업데이트가 되니 괜찮을 것 같다고 생각합니다
따로 초기화를 해주신 이유는 혹시 모를 sideEffect 때문인가요?

2023-01-06 18:04 UTC, J1min requested changes
hooks 분리하신 부분이 인상깊네요
저도 custom hooks의 장인이 되도록 노력하겠습니다 👍🏻

2023-01-06 18:06 UTC, J1min approved these changes

2023-01-07 02:55 UTC, J1min approved these changes

2023-01-07 03:01 UTC, pkiop commented on store/modal.tsx
> +export const MODAL_STATE = "MODAL_STATE";
이 key값을 여러군데서 쓸 것 같아 매직 리터럴로 뺐는데
리코일 사용법 보니 이 키값은 다른데 쓰일 일이 없네요 수정했습니다👍

2023-01-07 03:04 UTC, pkiop commented on hooks/useModal.ts
> +  const closeModal = () => {
title이랑 content 타입이 optional 이 아니라 넣어줘야 했어요~
옵셔널로하고 말씀하신대로 open할 때 업데이트하도록 해도 되지만 옵셔널로 하고싶진 않아서요!

2023-01-07 03:04 UTC, merged

2023-01-07 03:08 UTC, J1min commented on hooks/useModal.ts
> +  const closeModal = () => {
아하 그런 이유가 있는줄 몰랐습니다 저도 최대한 optional은 지양하도록 하겠습니다 👍

2023-01-07 03:12 UTC, J1min commented
선생님 저는 main, 현재 작업중인 브랜치 이외에는 머지한 이후 바로바로 삭제하는 편인데 선생님께선 브랜치를 삭제하지 않으시는 이유가 궁금합니다 🤔